 #Bem-vindo usuario!
#

# Site settings
title: Tia Aurora Pet/Flora
description: |
  Bem-vindo ao nosso site, caro amante de animais e flores.
  Aqui voce encontra as melhores rações para seu amiguinho, brinquedos,petisto, entre outros. 
  Além de claro, um ambiente floral e várias dicas para um melhor cuidado com a sua floração.  
owner: Tia Aurora # or company name
first_published: 2021 # if migrating another site, the year of your first publish
email: auroradutraengambiental@hotmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter : 
  github: https://github.com/vitoriaaugusta
  email: https://vitoriacastrosoares@gmail.com
  #flickr:
  instagram: https://www.instagram.com/tia_aurora_petflora/
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
